### ISSUE TITLE
Azure-Cloud-Integration-Test is broken on main branch

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2253]
# Bug Report

## Describe the Bug
`Azure-Cloud-Integration-Test` is broken on main branch
https://github.com/eclipse-edc/Connector/actions/runs/3572501421/jobs/6005477188

### Expected Behavior
-

### Observed Behavior
-

## Steps to Reproduce
-
## Context Information
-

## Detailed Description
-

## Possible Implementation
-

**Comment by paullatzelsperger** [comment]
The problem was related to expired credentials, which now seems to be [resolved](https://github.com/eclipse-edc/Connector/actions/runs/3723517125). However, it seems the test is still [flaky](https://github.com/eclipse-edc/Connector/actions/runs/3728832563/jobs/6324173720). That is a different problem though.

**Comment by ndr-brt** [comment]
@paullatzelsperger I'm ok with closing this and create another one
