### ISSUE TITLE
TransferProcess is not possible from a connector to itself

### ISSUE THREAD

**Issue by git-masoud** [eclipse-edc/Connector#2283]
# Bug Report

## Describe the Bug
Once you trigger a transferProcess form a connector to itself, nothing happens. Looking at the connector's logs, you only see that consumer initiates a process and its state changes to completed, no logs from the provider.

### Expected Behavior
Connector should process the transfer request and trigger the dataplane for the data exchange.

### Observed Behavior
Connector as consumer create a TransferProcess and sends the request to itself as the provider. 
Since both consumer and provider share a same transferProcessStore, provider doesn't generate a new process and returns the consumer process which is already in the _completed_ state.

## Steps to Reproduce
Trigger the transfer process and leave itself Ids endpoint as connectorAddress 

## Possible Implementation
Two approaches to solve this issue:

1. Currently provider try to generates the same Id as the consumer. Problem will be solved by generating a new Id. there could be some reasons that it is being done in this way. To do that we can simply change the _DataRequestId_ to a new `UUID` instead of `message.getId().toString()` in _ArtifactRequestHandler_.
2. `processIdForDataRequestId` functions in all the TransferProcessStores should filter the `processId` together with the `TransferProcess.Type
`  

 `
String processIdForDataRequestId(String id);` **->** `String processIdForDataRequestId(String id, TransferProcess.Type type)`

**Comment by jimmarino** [comment]
Changing the tag because this is not a bug.

We used to have something similar using a special loopback protocol (in place of IDS). However, this is no longer needed since multiple connector instances can be run in the same process using the JUnit launcher.

We shouldn't change the `ArtifactRequestHandler` or the `TransferProcessStore` implementations as this will pollute critical code paths to handle a configuration that is never used in a realistic deployment.

**Comment by git-masoud** [comment]
Sorry for the late reply and thanks a lot for the feedback. 
This request originally came from one of the projects within Catena-x, and I am still waiting to learn more about the purpose behind it.
However, it would be useful to have this feature for testing the connector's(provider) functionality after deployment. A successful transfer process of a connector to itself proves all the components such as Identity provider, DPF, Dataplanes configurations are properly set up and functioning as intended.

**Comment by jimmarino** [comment]
It sounds like what is needed is an end-to-end integration test that launches multiple services in a dataspace. In that case, multiple connectors and supporting services should be launched. If you want to verify an actual *deployment* then you need to create a replicated test environment (e.g., containers, clusters, etc.). Think about it this way: do you want to test that a connector trusts itself, or do you want to verify a real-world data exchange scenario between two participants?

Otherwise, if what is needed is a sample that can be easily debugged for learning purposes, using the existing JUnit launcher is dead simple and fits the bill. The introduction of the JUnit multi-instance launcher obviated the need to support a loopback protocol for this purpose.
