### ISSUE TITLE
dsp: contract offer `id` is set to the offer in the catalog but not mapped from/to `Policy`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2921]
# Feature Request

`JsonObjectFromDatasetTransformer` puts the offer id as the Policy `@id`, but both of `JsonObjectFromPolicyTransformer` and `JsonObjectToPolicyTransformer` does not map it correctly.

Our `Policy` model class misses the `uid` field that's considered mandatory in the odrl specs: https://www.w3.org/TR/odrl-model/#policy
so maybe it's time to add it (again) to the `Policy` object

## Which Areas Would Be Affected?
_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?
_Are there any requirements?_

## Solution Proposal
_If possible, provide a (brief!) solution proposal._

**Comment by jimmarino** [comment]
In the IDS specification working group we decided to profile ODRL to use `@id` instead of `uid` since it is the correct Json-ld form (ODRL existed before Json-ld). I'll look to see see if we can add an id to the policy.

**Comment by jimmarino** [comment]
> In that case I think we'll need to change the field name in `Rule` as well (as it's extending `Identifiable`), to have `id` everywhere

For Rule, I'm going to remove `Identifiable` since per the ODRL spec a Rule [does not need an identifier](https://www.w3.org/TR/odrl-model/#rule). The `uid` field is only used on Rule if it needs to be referenced from another context, which we don't need. 

The ODRL spec does mandate a `uid` field for `Policy.` We have ids for `ContractOffer` and `ContractAgreement`, which map to ODRL `Offer` and `Agreement`, and these are properly handled by the transformers. We don't need to have an id on the internal `Policy` type because it acts as a fragment of a containing entity such as `ContractOffer`, `ContractAgreement`, and `ContractDefinition`.  

So for this PR, I'll remove `Identifiable` and perform a few minor cleanup tasks in the related transformer.

Let me know if I've missed something.

**Comment by jimmarino** [comment]
PR here #2938 #2938
