### ISSUE TITLE
DSP: EDC expects a certain agreementId string format

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Connector#3240]
It seems EDC expects a certain agreementId string format that is parsed and split into different other properties. This is not according to the specs and stops other DSP implementations.

```
        var contractId = ContractId.parse(agreement.getId());
        if (!contractId.isValid()) {
            return failure(format("ContractId %s does not follow the expected schema.", agreement.getId()));
        }

```

```
     * Return a {@link ContractId} instance parsed from the passed string, that should be in the
     * <code>[definition-id]:UUID</code> format

```

version 0.1.0

endpoint `/negotiations/{process_id}/agreement`

Can someone please check?

Thanks

--
Matthias Binzer

**Comment by jimmarino** [comment]
There are two cases where the agreement ID is parsed:

1. On the consumer side (shown above):

```
 public Result<Void> validateConfirmed(ClaimToken token, ContractAgreement agreement, ContractOffer latestOffer) {
        // ....
        var contractId = ContractId.parse(agreement.getId());
        if (!contractId.isValid()) {
            return failure(format("ContractId %s does not follow the expected schema.", agreement.getId()));
        }

```
This is incorrect, and we can just remove the validation since the agreement originates on the provider (which could be a different DSP implementation).

2. On the provider side:

```
  public Result<Void> validateConfirmed(ClaimToken token, ContractAgreement agreement, ContractOffer latestOffer) {
        // ....
        var contractId = ContractId.parse(agreement.getId());
        if (!contractId.isValid()) {
            return failure(format("ContractId %s does not follow the expected schema.", agreement.getId()));
        }
```

This is correct, as the agreement always originates on the provider (the current runtime type, i.e. EDC). 

From a spec perspective, this is fine since the spec does not require anything other than the ID is a globally unique string and that the consumer runtimes must accept what the provider issues.

**Comment by matgnt** [comment]
Yes, absolutely correct! I was talking only about the EDC as consumer and non-EDC as a provider case. I fully agree, case 2 as a provider, EDC can of course do that. As a consumer, though, the validation must be removed.

Thanks for looking into this!
