### ISSUE TITLE
Publish `public` api context into dedicated swagger hub page

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3373]
One issue that I see here is that the data-plane public api should not be under the "control-api", because it's not an internal api meant to be used in the intra-connector communication but it is a public endpoint, in fact it is exposed on the "public" context, it should end up into a dedicated openapi spec file.

_Originally posted by @ndr-brt in https://github.com/eclipse-edc/Connector/discussions/3371#discussioncomment-6748465_

**Comment by hamidonos** [comment]
May I pick up this issue? @ndr-brt

**Comment by ndr-brt** [comment]
@hamidonos sure, just assign it to you

**Comment by hamidonos** [comment]
@ndr-brt The `DataPlanePublicApi` is part of the `data-plane:data-plane-api` module which is part of the `control-api` group. The group is set on module level by the `build.gradle.kts` file. I cannot simply change the group since this would affect all other apis inside this module.

I see two possible solutions

1. Split the `data-plane:data-plane-api` module in two modules `data-plane:data-plane-api` & `data-plane:data-plane-public-api`
2. Change the mechanism on how spec files are picked up. Most likely inside the `apidoc.yaml`.

With 1. dependency issues will arise in edc downstream because a new module is introduced unless `data-plane:data-plane-public-api` is defined as a transitive dependency of `data-plane:data-plane-api` then nothing will happen. I don't think this transitive dependency makes sense tho.

I think we should go with a version of solution 1 unless there is a completely different way to solve this which im currently unaware of :)

**Comment by ndr-brt** [comment]
I think the best way to do this would be to extract a `data-plane-public-api` module, and make `data-plane-api` depends on it, so there will be no change for downstream project and there will be the possibility to configure different api group in the build files.

**Comment by jimmarino** [comment]
> @ndr-brt The `DataPlanePublicApi` is part of the `data-plane:data-plane-api` module which is part of the `control-api` group. The group is set on module level by the `build.gradle.kts` file. I cannot simply change the group since this would affect all other apis inside this module.
> 
> I see two possible solutions
> 
> 1. Split the `data-plane:data-plane-api` module in two modules `data-plane:data-plane-api` & `data-plane:data-plane-public-api`
> 2. Change the mechanism on how spec files are picked up. Most likely inside the `apidoc.yaml`.
> 
> With 1. dependency issues will arise in edc downstream because a new module is introduced unless `data-plane:data-plane-public-api` is defined as a transitive dependency of `data-plane:data-plane-api` then nothing will happen. I don't think this transitive dependency makes sense tho.
> 
> I think we should go with a version of solution 1 unless there is a completely different way to solve this which im currently unaware of :)

+1 on approach 1 and without the transitive dependency. The change should be noted in the release notes and downstream projects will need to adjust.

**Comment by jimmarino** [comment]
> `data-plane-public-api`

I don't think the public API module should be coupled to the control API. `ResponseFunctions` is used by both APIs, but the individual methods can be refactored and broken up.
