### ISSUE TITLE
Adoption Request

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#3638]
---
name: Adoption Request
about: Submit your feature to the project
title: 'Adoption Request'
labels: 'adoption'
assignees: ''

---

# Adoption Request

This adoption request aims at contributing a new technology feature pack in the form of a new Technology Repository.
The contributing company is Huawei Technologies Co., Ltd.

The contribution initially will contain two major feature areas:
- OBS: S3-compatible object storage hosted in the cloud
- GaussDB: a relational database based on Postgres 9.2.4 as data retention backend

These components are currently implemented using EDC SPIs and core features.

## General information

Please provide some information about your project or code contribution. 

_If you choose to be referenced as a "friend", these will be added to the [known friends list](https://github.com/eclipse-edc/docs/blob/main/KNOWN_FRIENDS.md)._
_If you choose to add your feature as a core EDC component, links to your current code and correlated issues, discussions, and pull requests are of great importance._

| Title | Description | Contact | Links
| :--- | :--- | :--- | :---
| Huawei Dataspace Components | Technology repository named "Technology-Huawei" containing OBS extensions and GaussDB extensions | atul.athavale@huawei.com, chenliang613@huawei.com, swaroop.akulu.raghupathy@huawei.com   | https://github.com/Huawei-Dataspace-Components/components

## Adoption level

Next, please tell us what level of adoption you intend to provide. _(pick only one)_

- [ ] Reference a feature as "friend"
- [x] Incorporate a feature as core EDC component

## Adoption in EDC core

During an initial ramp-up phase, Huawei Technologies Co., Ltd. contracts existing committers of the EDC Technical Committers group to maintain and develop the code base. This phase will be supported and accompanied by two Huawei employees. Over time, Huawei Technologies Co., Ltd. will build up an internal team to take over maintenance of the `Technology-Huawei` repository.

Huawei Technologies Co., Ltd. commits to provide real cloud test infrastructure, if no self-contained (containerized) variant is available.

_If you chose to add your feature as a core EDC component, please answer the following questions._

### Why should this contribution be adopted?
> This contribution provides functionality based on the Huawei Cloud analogous to existing hyperscaler technology repositories.

### Could it be achieved with existing functionality? If not, why?
> No, because it is a novel development. Although large areas of the functionality provided herein are similar to existing implementations (OBS ~ S3, GaussDB ~ Postgres), there are customizations and subtle differences necessary. Futhermore, the testing environment is different.

### Are there multiple use cases or applications who will benefit from the contribution?
> Everyone who wants to leverage Huawei Cloud, which is relevant especially in non-European geographies.

### Can it be achieved without introducing third-party dependencies? If not, which ones?
> No, it cannot. The newly introduced dependencies are:
> - `com.huaweicloud:esdk-obs-java`: SDK to communicate with Object Storage Service
> - `com.huaweicloud.sdk:huaweicloud-sdk-iam`: SDK to communicate with the IAM service. Relevant for provisioning buckets.
> - `com.huaweicloud.dws:huaweicloud-dws-jdbc`: JDBC driver for GaussDB <br/>
> _all are resolvable from MavenCentral_

### Would this feature limit platform independence in any way? If so, how and why?
> No, the code would be platform-independent, although an active subscription for GaussDB / OBS is necessary.

### Is it going to be a self-contained feature, or would it cut across the entire code base?
> It is self-contained

**Comment by mspiekermann** [comment]
The committers have given the Huawei Technologies Ltd.'s adoption request a positive reception. We have observed Huawei's ongoing commitment to and support of the EDC. It's great to see another CSP embracing the EDC framework as well as participating in community support and delivering and maintaining customized extensions. These have a significant impact on the EDC's recognition on an international level.

We see no issues with the submitted codebase, and both extensions satisfy the EDC project's principles and contribution requirements. Both extensions, however, are brand-new creations and are unable to yet demonstrate the maintenance and track records that we have established as essential prerequisites and quality gates for acceptance in the EDC codebase. Even for extensions for technologies invented by the individual CSPs, this concrete proof is necessary in order to be branded with the Eclipse project and must adhere to the same ruleset as all other prior requests.

As a result, we will choose to accept the adoption once these conditions are met. Specifically, the TC has voted in favor of including Huawei-specific extensions in a technology folder going forward. However, prior to that, we must observe a history of consistent upkeep and application of the offered extensions. We therefore urge the Huawei team to demonstrate that they would maintain the extensions current for future iterations of the EDC and to showcase the application of these technologies in dataspace initiatives. One possible solution for this could be to attend one of our 2024 Q&A events and give a presentation. There is a clear path for integrating a technology repository for Huawei's extensions and the TC will resubmit the adoption request around Easter. 

Meanwhile, we will list the extensions on the known friends list to provide visibility within the community.
