### ISSUE TITLE
refactor(test): improve `QueryValidator` testing strategy

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3731]
# Feature Request

Currently the `QueryValidator` is tested integrated within the services, that's not a great approach.
It would be better to separate the responsibility (test the behavior in the validator test and the interaction in the service test)

## Which Areas Would Be Affected?

tests

## Why Is the Feature Desired?

avoid unnecessary integration tests

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by enchobelezirev** [comment]
Hello,

Can I take this issue?

Thanks!

**Comment by ndr-brt** [comment]
sure, I assigned it to you

**Comment by enchobelezirev** [comment]
@ndr-brt  Thanks!

**Comment by enchobelezirev** [comment]
Hello @ndr-brt,

Just checking to see whether I am on the right track for the issue. As far as I understood the issue it is needed to create a Mock objects of QueryValidator in the "*Service" classes in order to test whether the methods from the Services classes are reacted as expected when the QueryValidator either fails or succeeds during the validation, this is one thing. The other thing is to, possibly, extract the methods from the Service classes which are testing the actual usage of the QueryValidator in a separated "Integration" test.

Please, correct me if I did not get the issue correct.
Thanks!

**Comment by ndr-brt** [comment]
@enchobelezirev the `QueryValidator` is currently instantiated in the services constructor:
- `ContractAgreementServiceImpl`
- `ContractDefinitionServiceImpl`
- `ContractNegotiationServiceImpl`
- `PolicyDefinitionServiceImpl`
- `TransferProcessServiceImpl`

and its behavior is tested in the test service class (e.g. `TransferProcessServiceImplTest.search_validFilter`).
This is not good because a change in the query validator could result in multiple failing service tests.

As reported in the issue, the service test should verify the __interaction__ with the `queryValidator` (and it would need to be injected for that, instead of being instantiated in the constructor as it is now).

Then those validator tests should be moved in a separate place, a good approach could be to have a QueryValidatorFactory that creates instances for different services and some tests that verifies the object created behave in the  expected way

**Comment by enchobelezirev** [comment]
I did it without the Factory because I thought that the way of creation of QueryValidator should not be changed. If you do not like it, I will change it.

Thanks for the support! :)

**Comment by harnvo** [comment]
Hi,

given the previous PR is no longer active, I would like to take a look at this issue when I am available.

It might take sometime before the final PR (My dev machine is currently unavailble), but I would like to open a draft PR within a week to see if I am on the right track.
