### ISSUE TITLE
`Policy` "profile" cannot be retrieved

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3961]
# Feature Request

If the `odrl:profile` field is added to a new policy, it somewhat gets lost.
Ref. https://github.com/eclipse-tractusx/tractusx-edc/issues/1099

## Which Areas Would Be Affected?

policy

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by matgnt** [comment]
Thanks @ndr-brt for taking this issue upstream!

One thing I recognized is, that especially in case a 2nd connector (not EDC) does support this ODRL field and has it in its catalog it fails with EDC as a consumer connector, because the offers send around do not match because even then, the field is ignored, meaning not only when creating the policy, but also during the negotiation process.

```
DEBUG 2024-03-06T09:34:45.548642949 [Consumer] Contract agreement received. Validation failed: Policy in the contract agreement is not equal to the one in the contract offer
```

**Comment by saschaisele-zf** [comment]
I would take a look here.
@ndr-brt you can assign me here.

**Comment by ndr-brt** [comment]
hey @saschaisele-zf the PR got closed by the stalebot, are you still working on this issue?

**Comment by saschaisele-zf** [comment]
Progress has stalled for a while, but I will reopen it today with some additions
