### ISSUE TITLE
feature request: Implement "Before" event in asset, policy, contract definition in their corresponding Listener classes

### ISSUE THREAD

**Issue by suh-rao** [eclipse-edc/Connector#4006]
# Feature Request

Having an event before entities saved into DB useful. 

## Which Areas Would Be Affected?

Asset, Contract Definition and Policy definition entities

## Why Is the Feature Desired?

Currently during entities creation only created , updated, deleted(i.e (After entities saved in DB)
It will be help if an event triggerred before saved to DB. With this it is possible add or modify json field private properties.
For examle: It may be necessary to add administrative fields like createdBy, modifiedBy, modifiedAt etc. These shouldn't be passed from api as privateProperties rather has to be inserted from application before update to DB.

## Solution Proposal

In AssetListener, ContractDefinitionListener, ContractDefinitionListener, PolicyDefinitionListener add new methods
beforeCreate, beforeUpdate, beforeDelete.

In entities corresponding service implementation class
for ex: AssetServiceImpl -> create, update, delete call listeners method beforeCreate, or beforeUpdate or beforeDelete before saving it into DB

**Comment by ndr-brt** [comment]
This can actually already be done registering a request filter on the Jersey layer

**Comment by suh-rao** [comment]
With listeners, will get event after validation, transformation is completed. It is same after event we have it now in listener.

**Comment by ndr-brt** [comment]
I was just saying that what you are proposing is already doable in a some way, something similar could be achieved using stored procedures.

**Comment by suh-rao** [comment]
Currently we implemented required changes in BEFORE UPDATE TRIGGER.( https://www.postgresql.org/docs/current/sql-createtrigger.html). But it will be good if this can be supported in listeners. With that then will have uniformity over after, before events.

**Comment by ndr-brt** [comment]
is better not to confuse this "before" thing with "events", because events, by a globally shared definition (and also as [defined in the related decision record](https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2022-06-03-event-framework#instance-level)) are a representation of something that happened in the past, and they are a part of the EDC architecture with specific needs (e.g. triggering certain actions after something happens). 

I would not speak about "uniformity", what you are referring to is some sort of "data modification interceptor" that, as I said, it can already be obtained by a trigger stored procedure.
