### ISSUE TITLE
Warnings in management-api documentation lead to incorrectly generated clients

### ISSUE THREAD

**Issue by jhauckisst** [eclipse-edc/Connector#4115]
# Bug Report

## Describe the Bug

Warnings:
 - Unused model: JsonArray  
 - Unused model: JsonValue
 - Unused model: JsonObject

 These warnings show up when the *eclipse-edc-bot-management-api-0.6.0-resolved.yaml* (Source: [swaggerhub.com](https://app.swaggerhub.com/apis/eclipse-edc-bot/management-api/0.6.0#/info)) is used with the openAPI-Generator (JAR Version 7.4.0) and the command "validate".  

 Similar warnings also show up on [swaggerhub.com](https://app.swaggerhub.com/apis/eclipse-edc-bot/management-api/0.6.0#/info):  
 *Line 2170, Definition was declared but never used in document*  
 *Line 2190, Definition was declared but never used in document* 

### Expected Behavior

No warnings in the management-api document about unused models

### Observed Behavior

Warnings:
 - Unused model: JsonArray  
 - Unused model: JsonValue
 - Unused model: JsonObject

## Context Information

Warnings in versions:

- management-api 0.6.0
- management-api 0.5.1
- management-api 0.5.0

## Detailed Description
When trying to generate a python client with the openAPI-generator and the above mentioned management-api document, errors are present in the generated client. The errors are syntax errors and are linked to the JsonArray and JsonValue classes.  
 If the definitions of JsonArray, JsonValue and JsonObject are removed from the management-api document these syntax errors are not generated in the python client.

**Comment by ndr-brt** [comment]
those are unfortunately generated by the swagger documentation generator tool we're using, I remember I did a short investigation looking for excluding them but I didn't find a way to do it.

A general suggestion here is to avoid generated clients because they don't typically work well with json-ld.
There are some open source client implementations already available, it could worth taking a glance:
- Java: https://github.com/Think-iT-Labs/edc-connector-client-java
- TypeScript: https://github.com/Think-iT-Labs/edc-connector-client
